import type { User, Team, DealStage, Deal, Company, Contact } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Ana García",
    email: "ana@example.com",
    role: "CEO",
    level: 1,
    managerId: null,
    teamId: null,
    image: null,
  },
  {
    id: "2",
    name: "Carlos Rodríguez",
    email: "carlos@example.com",
    role: "Gerente de Ventas",
    level: 2,
    managerId: "1",
    teamId: "team1",
    image: null,
  },
  {
    id: "3",
    name: "María López",
    email: "maria@example.com",
    role: "Gerente de Marketing",
    level: 2,
    managerId: "1",
    teamId: "team2",
    image: null,
  },
  {
    id: "4",
    name: "Juan Pérez",
    email: "juan@example.com",
    role: "Ejecutivo de Ventas",
    level: 3,
    managerId: "2",
    teamId: "team1",
    image: null,
  },
  {
    id: "5",
    name: "Laura Martínez",
    email: "laura@example.com",
    role: "Ejecutivo de Ventas",
    level: 3,
    managerId: "2",
    teamId: "team1",
    image: null,
  },
  {
    id: "6",
    name: "Diego Fernández",
    email: "diego@example.com",
    role: "Especialista en Marketing",
    level: 3,
    managerId: "3",
    teamId: "team2",
    image: null,
  },
]

export const mockTeams: Team[] = [
  {
    id: "team1",
    name: "Equipo de Ventas",
    description: "Equipo dedicado a cerrar negocios",
    leaderId: "2",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "team2",
    name: "Equipo de Marketing",
    description: "Equipo de generación de leads",
    leaderId: "3",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockStages: DealStage[] = [
  {
    id: "stage1",
    name: "Oportunidad",
    order: 1,
    color: "#3b82f6",
    isDefault: true,
    isActive: true,
    createdBy: "1",
    companyOwnerId: null,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "stage2",
    name: "Cotización",
    order: 2,
    color: "#f59e0b",
    isDefault: true,
    isActive: true,
    createdBy: "1",
    companyOwnerId: null,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "stage3",
    name: "Negociación",
    order: 3,
    color: "#8b5cf6",
    isDefault: true,
    isActive: true,
    createdBy: "1",
    companyOwnerId: null,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "stage4",
    name: "Cerrado",
    order: 4,
    color: "#10b981",
    isDefault: true,
    isActive: true,
    createdBy: "1",
    companyOwnerId: null,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
]

export const mockCompanies: Company[] = [
  {
    id: "comp1",
    name: "Tech Solutions SA",
    email: "info@techsolutions.com",
    phone: "+54 11 4567-8901",
    website: "www.techsolutions.com",
    address: "Av. Córdoba 1234, CABA",
    industry: "Tecnología",
    employeeCount: 50,
    notes: "Cliente potencial de software empresarial",
    createdBy: "2",
    assignedTeamId: "team1",
    isGlobal: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "comp2",
    name: "Industrias del Sur",
    email: "contacto@indelsur.com",
    phone: "+54 11 5678-9012",
    website: "www.indelsur.com",
    address: "Av. Belgrano 5678, CABA",
    industry: "Manufactura",
    employeeCount: 200,
    notes: "Interesados en sistema de gestión",
    createdBy: "4",
    assignedTeamId: "team1",
    isGlobal: false,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "comp3",
    name: "Marketing Pro",
    email: "hola@marketingpro.com",
    phone: "+54 11 6789-0123",
    website: "www.marketingpro.com",
    address: "Av. Santa Fe 3456, CABA",
    industry: "Marketing",
    employeeCount: 30,
    notes: "Agencia de marketing digital",
    createdBy: "6",
    assignedTeamId: "team2",
    isGlobal: false,
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
]

export const mockContacts: Contact[] = [
  {
    id: "cont1",
    userId: "2",
    companyId: "comp1",
    name: "Roberto Sánchez",
    email: "rsanchez@techsolutions.com",
    phone: "+54 11 4567-8901",
    position: "Director de IT",
    status: "cliente",
    notes: "Tomador de decisiones principal",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "cont2",
    userId: "4",
    companyId: "comp2",
    name: "Patricia Gómez",
    email: "pgomez@indelsur.com",
    phone: "+54 11 5678-9012",
    position: "Gerente de Operaciones",
    status: "prospecto",
    notes: "Interesada en automatización",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "cont3",
    userId: "6",
    companyId: "comp3",
    name: "Martín Álvarez",
    email: "malvarez@marketingpro.com",
    phone: "+54 11 6789-0123",
    position: "CEO",
    status: "lead",
    notes: "Primera reunión programada",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
]

export const mockDeals: Deal[] = [
  {
    id: "deal1",
    userId: "4",
    contactId: "cont1",
    companyId: "comp1",
    title: "Implementación CRM Enterprise",
    currency: "USD",
    amountUsd: 85000,
    amountArs: null,
    dollarRate: 1350,
    exchangeRateId: null,
    stageId: "stage2",
    probability: 70,
    expectedCloseDate: new Date("2025-03-15"),
    closedAt: null,
    lostReason: null,
    notes: "Negociación avanzada, esperando aprobación de presupuesto",
    createdAt: new Date("2025-01-10"),
    updatedAt: new Date("2025-01-25"),
  },
  {
    id: "deal2",
    userId: "4",
    contactId: "cont2",
    companyId: "comp2",
    title: "Sistema de Gestión de Inventario",
    currency: "ARS",
    amountUsd: null,
    amountArs: 12500000,
    dollarRate: null,
    exchangeRateId: null,
    stageId: "stage1",
    probability: 40,
    expectedCloseDate: new Date("2025-04-20"),
    closedAt: null,
    lostReason: null,
    notes: "Primera reunión completada",
    createdAt: new Date("2025-02-05"),
    updatedAt: new Date("2025-02-05"),
  },
  {
    id: "deal3",
    userId: "5",
    contactId: "cont1",
    companyId: "comp1",
    title: "Capacitación y Soporte Anual",
    currency: "USD",
    amountUsd: 24000,
    amountArs: null,
    dollarRate: 1350,
    exchangeRateId: null,
    stageId: "stage3",
    probability: 85,
    expectedCloseDate: new Date("2025-03-01"),
    closedAt: null,
    lostReason: null,
    notes: "Contrato en revisión legal",
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-02-15"),
  },
  {
    id: "deal4",
    userId: "6",
    contactId: "cont3",
    companyId: "comp3",
    title: "Consultoría Digital",
    currency: "ARS",
    amountUsd: null,
    amountArs: 8500000,
    dollarRate: null,
    exchangeRateId: null,
    stageId: "stage2",
    probability: 60,
    expectedCloseDate: new Date("2025-03-30"),
    closedAt: null,
    lostReason: null,
    notes: "Propuesta enviada, esperando feedback",
    createdAt: new Date("2025-02-10"),
    updatedAt: new Date("2025-02-20"),
  },
  {
    id: "deal5",
    userId: "5",
    contactId: "cont2",
    companyId: "comp2",
    title: "Migración Cloud",
    currency: "USD",
    amountUsd: 45000,
    amountArs: null,
    dollarRate: 1350,
    exchangeRateId: null,
    stageId: "stage1",
    probability: 35,
    expectedCloseDate: new Date("2025-05-15"),
    closedAt: null,
    lostReason: null,
    notes: "Evaluando opciones",
    createdAt: new Date("2025-02-12"),
    updatedAt: new Date("2025-02-12"),
  },
  {
    id: "deal6",
    userId: "4",
    contactId: "cont1",
    companyId: "comp1",
    title: "Integración API Custom",
    currency: "USD",
    amountUsd: 18000,
    amountArs: null,
    dollarRate: 1350,
    exchangeRateId: null,
    stageId: "stage4",
    probability: 95,
    expectedCloseDate: new Date("2025-02-28"),
    closedAt: null,
    lostReason: null,
    notes: "Contrato firmado, inicio próxima semana",
    createdAt: new Date("2025-01-05"),
    updatedAt: new Date("2025-02-25"),
  },
  {
    id: "deal7",
    userId: "6",
    contactId: "cont3",
    companyId: "comp3",
    title: "Campaña de Redes Sociales",
    currency: "ARS",
    amountUsd: null,
    amountArs: 5500000,
    dollarRate: null,
    exchangeRateId: null,
    stageId: "stage3",
    probability: 75,
    expectedCloseDate: new Date("2025-03-10"),
    closedAt: null,
    lostReason: null,
    notes: "Último ajuste de presupuesto",
    createdAt: new Date("2025-02-01"),
    updatedAt: new Date("2025-02-22"),
  },
  {
    id: "deal8",
    userId: "5",
    contactId: "cont2",
    companyId: "comp2",
    title: "Dashboard de Métricas",
    currency: "USD",
    amountUsd: 32000,
    amountArs: null,
    dollarRate: 1350,
    exchangeRateId: null,
    stageId: "stage2",
    probability: 55,
    expectedCloseDate: new Date("2025-04-05"),
    closedAt: null,
    lostReason: null,
    notes: "Demo programada para próxima semana",
    createdAt: new Date("2025-02-08"),
    updatedAt: new Date("2025-02-18"),
  },
]
